version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    labels:
      - "dependencies"
      - "go"
    reviewers:
      - "openedr/maintainers"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    
  # Go modules for agent
  - package-ecosystem: "gomod"
    directory: "/agent"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    labels:
      - "dependencies"
      - "go"
      - "agent"
    reviewers:
      - "openedr/maintainers"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    
  # Go modules for server
  - package-ecosystem: "gomod"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    labels:
      - "dependencies"
      - "go"
      - "server"
    reviewers:
      - "openedr/maintainers"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    
  # Go modules for shared
  - package-ecosystem: "gomod"
    directory: "/shared"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    labels:
      - "dependencies"
      - "go"
      - "shared"
    reviewers:
      - "openedr/maintainers"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    
  # npm dependencies for web
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    labels:
      - "dependencies"
      - "javascript"
      - "web"
    reviewers:
      - "openedr/maintainers"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
    
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "openedr/maintainers"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    labels:
      - "dependencies"
      - "ci"
    reviewers:
      - "openedr/maintainers"
    commit-message:
      prefix: "chore(ci)"
      include: "scope" 