global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OpenEDR Server监控
  - job_name: 'openedr-server'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # OpenEDR Agent监控
  - job_name: 'openedr-agent'
    static_configs:
      - targets: ['host.docker.internal:9091']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node Exporter (系统指标)
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']

  # Docker容器监控
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL监控
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Elasticsearch监控
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'

  # Kafka监控
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092'] 