// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: shared/proto/common.proto

package common

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用响应状态
type Status int32

const (
	Status_STATUS_UNSPECIFIED  Status = 0
	Status_STATUS_SUCCESS      Status = 1
	Status_STATUS_ERROR        Status = 2
	Status_STATUS_TIMEOUT      Status = 3
	Status_STATUS_UNAUTHORIZED Status = 4
	Status_STATUS_NOT_FOUND    Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_SUCCESS",
		2: "STATUS_ERROR",
		3: "STATUS_TIMEOUT",
		4: "STATUS_UNAUTHORIZED",
		5: "STATUS_NOT_FOUND",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":  0,
		"STATUS_SUCCESS":      1,
		"STATUS_ERROR":        2,
		"STATUS_TIMEOUT":      3,
		"STATUS_UNAUTHORIZED": 4,
		"STATUS_NOT_FOUND":    5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_common_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_shared_proto_common_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_common_proto_rawDescGZIP(), []int{0}
}

// 日志级别
type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARN        LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
	LogLevel_LOG_LEVEL_FATAL       LogLevel = 5
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARN",
		4: "LOG_LEVEL_ERROR",
		5: "LOG_LEVEL_FATAL",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARN":        3,
		"LOG_LEVEL_ERROR":       4,
		"LOG_LEVEL_FATAL":       5,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_common_proto_enumTypes[1].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_shared_proto_common_proto_enumTypes[1]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_common_proto_rawDescGZIP(), []int{1}
}

// 事件类型
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_PROCESS     EventType = 1
	EventType_EVENT_TYPE_NETWORK     EventType = 2
	EventType_EVENT_TYPE_FILE        EventType = 3
	EventType_EVENT_TYPE_REGISTRY    EventType = 4
	EventType_EVENT_TYPE_DNS         EventType = 5
	EventType_EVENT_TYPE_LOGIN       EventType = 6
	EventType_EVENT_TYPE_SYSTEM      EventType = 7
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_PROCESS",
		2: "EVENT_TYPE_NETWORK",
		3: "EVENT_TYPE_FILE",
		4: "EVENT_TYPE_REGISTRY",
		5: "EVENT_TYPE_DNS",
		6: "EVENT_TYPE_LOGIN",
		7: "EVENT_TYPE_SYSTEM",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_PROCESS":     1,
		"EVENT_TYPE_NETWORK":     2,
		"EVENT_TYPE_FILE":        3,
		"EVENT_TYPE_REGISTRY":    4,
		"EVENT_TYPE_DNS":         5,
		"EVENT_TYPE_LOGIN":       6,
		"EVENT_TYPE_SYSTEM":      7,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_common_proto_enumTypes[2].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_shared_proto_common_proto_enumTypes[2]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_common_proto_rawDescGZIP(), []int{2}
}

// 威胁级别
type ThreatLevel int32

const (
	ThreatLevel_THREAT_LEVEL_UNSPECIFIED ThreatLevel = 0
	ThreatLevel_THREAT_LEVEL_INFO        ThreatLevel = 1
	ThreatLevel_THREAT_LEVEL_LOW         ThreatLevel = 2
	ThreatLevel_THREAT_LEVEL_MEDIUM      ThreatLevel = 3
	ThreatLevel_THREAT_LEVEL_HIGH        ThreatLevel = 4
	ThreatLevel_THREAT_LEVEL_CRITICAL    ThreatLevel = 5
)

// Enum value maps for ThreatLevel.
var (
	ThreatLevel_name = map[int32]string{
		0: "THREAT_LEVEL_UNSPECIFIED",
		1: "THREAT_LEVEL_INFO",
		2: "THREAT_LEVEL_LOW",
		3: "THREAT_LEVEL_MEDIUM",
		4: "THREAT_LEVEL_HIGH",
		5: "THREAT_LEVEL_CRITICAL",
	}
	ThreatLevel_value = map[string]int32{
		"THREAT_LEVEL_UNSPECIFIED": 0,
		"THREAT_LEVEL_INFO":        1,
		"THREAT_LEVEL_LOW":         2,
		"THREAT_LEVEL_MEDIUM":      3,
		"THREAT_LEVEL_HIGH":        4,
		"THREAT_LEVEL_CRITICAL":    5,
	}
)

func (x ThreatLevel) Enum() *ThreatLevel {
	p := new(ThreatLevel)
	*p = x
	return p
}

func (x ThreatLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThreatLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_common_proto_enumTypes[3].Descriptor()
}

func (ThreatLevel) Type() protoreflect.EnumType {
	return &file_shared_proto_common_proto_enumTypes[3]
}

func (x ThreatLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThreatLevel.Descriptor instead.
func (ThreatLevel) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_common_proto_rawDescGZIP(), []int{3}
}

// Agent信息
type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	OsVersion     string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Architecture  string                 `protobuf:"bytes,5,opt,name=architecture,proto3" json:"architecture,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	LastSeen      *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	IpAddress     string                 `protobuf:"bytes,8,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	MacAddress    string                 `protobuf:"bytes,9,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_shared_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_shared_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *AgentInfo) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *AgentInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentInfo) GetLastSeen() *timestamp.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *AgentInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AgentInfo) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *AgentInfo) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// 通用响应
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=openedr.common.Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_shared_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_shared_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Response) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// 分页信息
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_shared_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_shared_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 时间范围
type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_shared_proto_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_shared_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *TimeRange) GetStart() *timestamp.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TimeRange) GetEnd() *timestamp.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

var File_shared_proto_common_proto protoreflect.FileDescriptor

const file_shared_proto_common_proto_rawDesc = "" +
	"\n" +
	"\x19shared/proto/common.proto\x12\x0eopenedr.common\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x03\n" +
	"\tAgentInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\x12\"\n" +
	"\farchitecture\x18\x05 \x01(\tR\farchitecture\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion\x127\n" +
	"\tlast_seen\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x1d\n" +
	"\n" +
	"ip_address\x18\b \x01(\tR\tipAddress\x12\x1f\n" +
	"\vmac_address\x18\t \x01(\tR\n" +
	"macAddress\x127\n" +
	"\x04tags\x18\n" +
	" \x03(\v2#.openedr.common.AgentInfo.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x01\n" +
	"\bResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.openedr.common.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"S\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"k\n" +
	"\tTimeRange\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end*\x89\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x01\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x02\x12\x12\n" +
	"\x0eSTATUS_TIMEOUT\x10\x03\x12\x17\n" +
	"\x13STATUS_UNAUTHORIZED\x10\x04\x12\x14\n" +
	"\x10STATUS_NOT_FOUND\x10\x05*\x8c\x01\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x04\x12\x13\n" +
	"\x0fLOG_LEVEL_FATAL\x10\x05*\xc6\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_TYPE_PROCESS\x10\x01\x12\x16\n" +
	"\x12EVENT_TYPE_NETWORK\x10\x02\x12\x13\n" +
	"\x0fEVENT_TYPE_FILE\x10\x03\x12\x17\n" +
	"\x13EVENT_TYPE_REGISTRY\x10\x04\x12\x12\n" +
	"\x0eEVENT_TYPE_DNS\x10\x05\x12\x14\n" +
	"\x10EVENT_TYPE_LOGIN\x10\x06\x12\x15\n" +
	"\x11EVENT_TYPE_SYSTEM\x10\a*\xa3\x01\n" +
	"\vThreatLevel\x12\x1c\n" +
	"\x18THREAT_LEVEL_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11THREAT_LEVEL_INFO\x10\x01\x12\x14\n" +
	"\x10THREAT_LEVEL_LOW\x10\x02\x12\x17\n" +
	"\x13THREAT_LEVEL_MEDIUM\x10\x03\x12\x15\n" +
	"\x11THREAT_LEVEL_HIGH\x10\x04\x12\x19\n" +
	"\x15THREAT_LEVEL_CRITICAL\x10\x05B5Z3github.com/XXXXD-cation/OpenEDR/shared/proto/commonb\x06proto3"

var (
	file_shared_proto_common_proto_rawDescOnce sync.Once
	file_shared_proto_common_proto_rawDescData []byte
)

func file_shared_proto_common_proto_rawDescGZIP() []byte {
	file_shared_proto_common_proto_rawDescOnce.Do(func() {
		file_shared_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_common_proto_rawDesc), len(file_shared_proto_common_proto_rawDesc)))
	})
	return file_shared_proto_common_proto_rawDescData
}

var file_shared_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_shared_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_shared_proto_common_proto_goTypes = []any{
	(Status)(0),                 // 0: openedr.common.Status
	(LogLevel)(0),               // 1: openedr.common.LogLevel
	(EventType)(0),              // 2: openedr.common.EventType
	(ThreatLevel)(0),            // 3: openedr.common.ThreatLevel
	(*AgentInfo)(nil),           // 4: openedr.common.AgentInfo
	(*Response)(nil),            // 5: openedr.common.Response
	(*Pagination)(nil),          // 6: openedr.common.Pagination
	(*TimeRange)(nil),           // 7: openedr.common.TimeRange
	nil,                         // 8: openedr.common.AgentInfo.TagsEntry
	(*timestamp.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_shared_proto_common_proto_depIdxs = []int32{
	9, // 0: openedr.common.AgentInfo.last_seen:type_name -> google.protobuf.Timestamp
	8, // 1: openedr.common.AgentInfo.tags:type_name -> openedr.common.AgentInfo.TagsEntry
	0, // 2: openedr.common.Response.status:type_name -> openedr.common.Status
	9, // 3: openedr.common.Response.timestamp:type_name -> google.protobuf.Timestamp
	9, // 4: openedr.common.TimeRange.start:type_name -> google.protobuf.Timestamp
	9, // 5: openedr.common.TimeRange.end:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_shared_proto_common_proto_init() }
func file_shared_proto_common_proto_init() {
	if File_shared_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_common_proto_rawDesc), len(file_shared_proto_common_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_proto_common_proto_goTypes,
		DependencyIndexes: file_shared_proto_common_proto_depIdxs,
		EnumInfos:         file_shared_proto_common_proto_enumTypes,
		MessageInfos:      file_shared_proto_common_proto_msgTypes,
	}.Build()
	File_shared_proto_common_proto = out.File
	file_shared_proto_common_proto_goTypes = nil
	file_shared_proto_common_proto_depIdxs = nil
}
