// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: shared/proto/agent_service.proto

package agent

import (
	common "github.com/XXXXD-cation/OpenEDR/shared/proto/common"
	events "github.com/XXXXD-cation/OpenEDR/shared/proto/events"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent注册请求
type RegisterRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	AgentInfo              *common.AgentInfo      `protobuf:"bytes,1,opt,name=agent_info,json=agentInfo,proto3" json:"agent_info,omitempty"`
	CertificateFingerprint string                 `protobuf:"bytes,2,opt,name=certificate_fingerprint,json=certificateFingerprint,proto3" json:"certificate_fingerprint,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_shared_proto_agent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_agent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_agent_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentInfo() *common.AgentInfo {
	if x != nil {
		return x.AgentInfo
	}
	return nil
}

func (x *RegisterRequest) GetCertificateFingerprint() string {
	if x != nil {
		return x.CertificateFingerprint
	}
	return ""
}

// Agent注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Config        *AgentConfig           `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	NextHeartbeat *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=next_heartbeat,json=nextHeartbeat,proto3" json:"next_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_shared_proto_agent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_agent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_agent_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetConfig() *AgentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RegisterResponse) GetNextHeartbeat() *timestamp.Timestamp {
	if x != nil {
		return x.NextHeartbeat
	}
	return nil
}

// Agent配置
type AgentConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatInterval    int32                  `protobuf:"varint,1,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"` // seconds
	EventBatchSize       int32                  `protobuf:"varint,2,opt,name=event_batch_size,json=eventBatchSize,proto3" json:"event_batch_size,omitempty"`
	EventBatchTimeout    int32                  `protobuf:"varint,3,opt,name=event_batch_timeout,json=eventBatchTimeout,proto3" json:"event_batch_timeout,omitempty"` // seconds
	EnabledCollectors    []string               `protobuf:"bytes,4,rep,name=enabled_collectors,json=enabledCollectors,proto3" json:"enabled_collectors,omitempty"`
	CollectorConfigs     map[string]string      `protobuf:"bytes,5,rep,name=collector_configs,json=collectorConfigs,proto3" json:"collector_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LogConfig            *LogConfig             `protobuf:"bytes,6,opt,name=log_config,json=logConfig,proto3" json:"log_config,omitempty"`
	EnableRealTimeEvents bool                   `protobuf:"varint,7,opt,name=enable_real_time_events,json=enableRealTimeEvents,proto3" json:"enable_real_time_events,omitempty"`
	BlockedProcesses     []string               `protobuf:"bytes,8,rep,name=blocked_processes,json=blockedProcesses,proto3" json:"blocked_processes,omitempty"`
	BlockedDomains       []string               `protobuf:"bytes,9,rep,name=blocked_domains,json=blockedDomains,proto3" json:"blocked_domains,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_shared_proto_agent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_agent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_shared_proto_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *AgentConfig) GetHeartbeatInterval() int32 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

func (x *AgentConfig) GetEventBatchSize() int32 {
	if x != nil {
		return x.EventBatchSize
	}
	return 0
}

func (x *AgentConfig) GetEventBatchTimeout() int32 {
	if x != nil {
		return x.EventBatchTimeout
	}
	return 0
}

func (x *AgentConfig) GetEnabledCollectors() []string {
	if x != nil {
		return x.EnabledCollectors
	}
	return nil
}

func (x *AgentConfig) GetCollectorConfigs() map[string]string {
	if x != nil {
		return x.CollectorConfigs
	}
	return nil
}

func (x *AgentConfig) GetLogConfig() *LogConfig {
	if x != nil {
		return x.LogConfig
	}
	return nil
}

func (x *AgentConfig) GetEnableRealTimeEvents() bool {
	if x != nil {
		return x.EnableRealTimeEvents
	}
	return false
}

func (x *AgentConfig) GetBlockedProcesses() []string {
	if x != nil {
		return x.BlockedProcesses
	}
	return nil
}

func (x *AgentConfig) GetBlockedDomains() []string {
	if x != nil {
		return x.BlockedDomains
	}
	return nil
}

// 日志配置
type LogConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         common.LogLevel        `protobuf:"varint,1,opt,name=level,proto3,enum=openedr.common.LogLevel" json:"level,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"` // file, console, syslog
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	MaxFileSize   int32                  `protobuf:"varint,4,opt,name=max_file_size,json=maxFileSize,proto3" json:"max_file_size,omitempty"` // MB
	MaxBackups    int32                  `protobuf:"varint,5,opt,name=max_backups,json=maxBackups,proto3" json:"max_backups,omitempty"`
	MaxAge        int32                  `protobuf:"varint,6,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"` // days
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogConfig) Reset() {
	*x = LogConfig{}
	mi := &file_shared_proto_agent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogConfig) ProtoMessage() {}

func (x *LogConfig) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_agent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogConfig.ProtoReflect.Descriptor instead.
func (*LogConfig) Descriptor() ([]byte, []int) {
	return file_shared_proto_agent_service_proto_rawDescGZIP(), []int{3}
}

func (x *LogConfig) GetLevel() common.LogLevel {
	if x != nil {
		return x.Level
	}
	return common.LogLevel(0)
}

func (x *LogConfig) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *LogConfig) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *LogConfig) GetMaxFileSize() int32 {
	if x != nil {
		return x.MaxFileSize
	}
	return 0
}

func (x *LogConfig) GetMaxBackups() int32 {
	if x != nil {
		return x.MaxBackups
	}
	return 0
}

func (x *LogConfig) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

// 心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        *AgentStatus           `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Metrics       *AgentMetrics          `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_shared_proto_agent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_agent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_agent_service_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HeartbeatRequest) GetStatus() *AgentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *HeartbeatRequest) GetMetrics() *AgentMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Agent状态
type AgentStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Uptime           *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Status           string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // running, stopping, error
	ActiveCollectors []string               `protobuf:"bytes,4,rep,name=active_collectors,json=activeCollectors,proto3" json:"active_collectors,omitempty"`
	EventsProcessed  int64                  `protobuf:"varint,5,opt,name=events_processed,json=eventsProcessed,proto3" json:"events_processed,omitempty"`
	EventsSent       int64                  `protobuf:"varint,6,opt,name=events_sent,json=eventsSent,proto3" json:"events_sent,omitempty"`
	LastError        string                 `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_shared_proto_agent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_agent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatus.ProtoReflect.Descriptor instead.
func (*AgentStatus) Descriptor() ([]byte, []int) {
	return file_shared_proto_agent_service_proto_rawDescGZIP(), []int{5}
}

func (x *AgentStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentStatus) GetUptime() *timestamp.Timestamp {
	if x != nil {
		return x.Uptime
	}
	return nil
}

func (x *AgentStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentStatus) GetActiveCollectors() []string {
	if x != nil {
		return x.ActiveCollectors
	}
	return nil
}

func (x *AgentStatus) GetEventsProcessed() int64 {
	if x != nil {
		return x.EventsProcessed
	}
	return 0
}

func (x *AgentStatus) GetEventsSent() int64 {
	if x != nil {
		return x.EventsSent
	}
	return 0
}

func (x *AgentStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

// Agent性能指标
type AgentMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage          float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage       int64                  `protobuf:"varint,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"` // bytes
	DiskUsage         int64                  `protobuf:"varint,3,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`       // bytes
	ActiveConnections int32                  `protobuf:"varint,4,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	EventsPerSecond   int64                  `protobuf:"varint,5,opt,name=events_per_second,json=eventsPerSecond,proto3" json:"events_per_second,omitempty"`
	CollectorMetrics  map[string]float64     `protobuf:"bytes,6,rep,name=collector_metrics,json=collectorMetrics,proto3" json:"collector_metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AgentMetrics) Reset() {
	*x = AgentMetrics{}
	mi := &file_shared_proto_agent_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMetrics) ProtoMessage() {}

func (x *AgentMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_agent_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMetrics.ProtoReflect.Descriptor instead.
func (*AgentMetrics) Descriptor() ([]byte, []int) {
	return file_shared_proto_agent_service_proto_rawDescGZIP(), []int{6}
}

func (x *AgentMetrics) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *AgentMetrics) GetMemoryUsage() int64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *AgentMetrics) GetDiskUsage() int64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *AgentMetrics) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *AgentMetrics) GetEventsPerSecond() int64 {
	if x != nil {
		return x.EventsPerSecond
	}
	return 0
}

func (x *AgentMetrics) GetCollectorMetrics() map[string]float64 {
	if x != nil {
		return x.CollectorMetrics
	}
	return nil
}

// 心跳响应
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	NextHeartbeat *timestamp.Timestamp   `protobuf:"bytes,2,opt,name=next_heartbeat,json=nextHeartbeat,proto3" json:"next_heartbeat,omitempty"`
	Commands      []*AgentCommand        `protobuf:"bytes,3,rep,name=commands,proto3" json:"commands,omitempty"`
	UpdatedConfig *AgentConfig           `protobuf:"bytes,4,opt,name=updated_config,json=updatedConfig,proto3" json:"updated_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_shared_proto_agent_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_agent_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_agent_service_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *HeartbeatResponse) GetNextHeartbeat() *timestamp.Timestamp {
	if x != nil {
		return x.NextHeartbeat
	}
	return nil
}

func (x *HeartbeatResponse) GetCommands() []*AgentCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *HeartbeatResponse) GetUpdatedConfig() *AgentConfig {
	if x != nil {
		return x.UpdatedConfig
	}
	return nil
}

// Agent命令
type AgentCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	CommandType   string                 `protobuf:"bytes,2,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"` // restart, update_config, collect_info, isolate, etc.
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresAt     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommand) Reset() {
	*x = AgentCommand{}
	mi := &file_shared_proto_agent_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommand) ProtoMessage() {}

func (x *AgentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_agent_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommand.ProtoReflect.Descriptor instead.
func (*AgentCommand) Descriptor() ([]byte, []int) {
	return file_shared_proto_agent_service_proto_rawDescGZIP(), []int{8}
}

func (x *AgentCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *AgentCommand) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *AgentCommand) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *AgentCommand) GetExpiresAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// 命令执行结果
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        common.Status          `protobuf:"varint,3,opt,name=status,proto3,enum=openedr.common.Status" json:"status,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	ExecutedAt    *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_shared_proto_agent_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_agent_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_shared_proto_agent_service_proto_rawDescGZIP(), []int{9}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CommandResult) GetStatus() common.Status {
	if x != nil {
		return x.Status
	}
	return common.Status(0)
}

func (x *CommandResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResult) GetExecutedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

// 事件上报请求
type ReportEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	EventBatch    *events.EventBatch     `protobuf:"bytes,2,opt,name=event_batch,json=eventBatch,proto3" json:"event_batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportEventsRequest) Reset() {
	*x = ReportEventsRequest{}
	mi := &file_shared_proto_agent_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEventsRequest) ProtoMessage() {}

func (x *ReportEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_agent_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEventsRequest.ProtoReflect.Descriptor instead.
func (*ReportEventsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_agent_service_proto_rawDescGZIP(), []int{10}
}

func (x *ReportEventsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReportEventsRequest) GetEventBatch() *events.EventBatch {
	if x != nil {
		return x.EventBatch
	}
	return nil
}

// 事件上报响应
type ReportEventsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Response        *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	EventsReceived  int32                  `protobuf:"varint,2,opt,name=events_received,json=eventsReceived,proto3" json:"events_received,omitempty"`
	EventsProcessed int32                  `protobuf:"varint,3,opt,name=events_processed,json=eventsProcessed,proto3" json:"events_processed,omitempty"`
	FailedEventIds  []string               `protobuf:"bytes,4,rep,name=failed_event_ids,json=failedEventIds,proto3" json:"failed_event_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportEventsResponse) Reset() {
	*x = ReportEventsResponse{}
	mi := &file_shared_proto_agent_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportEventsResponse) ProtoMessage() {}

func (x *ReportEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_agent_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportEventsResponse.ProtoReflect.Descriptor instead.
func (*ReportEventsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_agent_service_proto_rawDescGZIP(), []int{11}
}

func (x *ReportEventsResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ReportEventsResponse) GetEventsReceived() int32 {
	if x != nil {
		return x.EventsReceived
	}
	return 0
}

func (x *ReportEventsResponse) GetEventsProcessed() int32 {
	if x != nil {
		return x.EventsProcessed
	}
	return 0
}

func (x *ReportEventsResponse) GetFailedEventIds() []string {
	if x != nil {
		return x.FailedEventIds
	}
	return nil
}

// 获取配置请求
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ConfigVersion string                 `protobuf:"bytes,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_shared_proto_agent_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_agent_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_agent_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetConfigRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetConfigRequest) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

// 获取配置响应
type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Config        *AgentConfig           `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	ConfigVersion string                 `protobuf:"bytes,3,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_shared_proto_agent_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_agent_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_agent_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetConfigResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GetConfigResponse) GetConfig() *AgentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetConfigResponse) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

// 日志条目
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Level         common.LogLevel        `protobuf:"varint,2,opt,name=level,proto3,enum=openedr.common.LogLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Component     string                 `protobuf:"bytes,5,opt,name=component,proto3" json:"component,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,6,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_shared_proto_agent_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_agent_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_shared_proto_agent_service_proto_rawDescGZIP(), []int{14}
}

func (x *LogEntry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *LogEntry) GetLevel() common.LogLevel {
	if x != nil {
		return x.Level
	}
	return common.LogLevel(0)
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *LogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// 日志上报请求
type ReportLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogEntry            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportLogsRequest) Reset() {
	*x = ReportLogsRequest{}
	mi := &file_shared_proto_agent_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportLogsRequest) ProtoMessage() {}

func (x *ReportLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_agent_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportLogsRequest.ProtoReflect.Descriptor instead.
func (*ReportLogsRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_agent_service_proto_rawDescGZIP(), []int{15}
}

func (x *ReportLogsRequest) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

// 日志上报响应
type ReportLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	LogsReceived  int32                  `protobuf:"varint,2,opt,name=logs_received,json=logsReceived,proto3" json:"logs_received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportLogsResponse) Reset() {
	*x = ReportLogsResponse{}
	mi := &file_shared_proto_agent_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportLogsResponse) ProtoMessage() {}

func (x *ReportLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_agent_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportLogsResponse.ProtoReflect.Descriptor instead.
func (*ReportLogsResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_agent_service_proto_rawDescGZIP(), []int{16}
}

func (x *ReportLogsResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ReportLogsResponse) GetLogsReceived() int32 {
	if x != nil {
		return x.LogsReceived
	}
	return 0
}

var File_shared_proto_agent_service_proto protoreflect.FileDescriptor

const file_shared_proto_agent_service_proto_rawDesc = "" +
	"\n" +
	" shared/proto/agent_service.proto\x12\ropenedr.agent\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19shared/proto/common.proto\x1a\x19shared/proto/events.proto\"\x84\x01\n" +
	"\x0fRegisterRequest\x128\n" +
	"\n" +
	"agent_info\x18\x01 \x01(\v2\x19.openedr.common.AgentInfoR\tagentInfo\x127\n" +
	"\x17certificate_fingerprint\x18\x02 \x01(\tR\x16certificateFingerprint\"\xda\x01\n" +
	"\x10RegisterResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.openedr.common.ResponseR\bresponse\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x122\n" +
	"\x06config\x18\x03 \x01(\v2\x1a.openedr.agent.AgentConfigR\x06config\x12A\n" +
	"\x0enext_heartbeat\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rnextHeartbeat\"\xaf\x04\n" +
	"\vAgentConfig\x12-\n" +
	"\x12heartbeat_interval\x18\x01 \x01(\x05R\x11heartbeatInterval\x12(\n" +
	"\x10event_batch_size\x18\x02 \x01(\x05R\x0eeventBatchSize\x12.\n" +
	"\x13event_batch_timeout\x18\x03 \x01(\x05R\x11eventBatchTimeout\x12-\n" +
	"\x12enabled_collectors\x18\x04 \x03(\tR\x11enabledCollectors\x12]\n" +
	"\x11collector_configs\x18\x05 \x03(\v20.openedr.agent.AgentConfig.CollectorConfigsEntryR\x10collectorConfigs\x127\n" +
	"\n" +
	"log_config\x18\x06 \x01(\v2\x18.openedr.agent.LogConfigR\tlogConfig\x125\n" +
	"\x17enable_real_time_events\x18\a \x01(\bR\x14enableRealTimeEvents\x12+\n" +
	"\x11blocked_processes\x18\b \x03(\tR\x10blockedProcesses\x12'\n" +
	"\x0fblocked_domains\x18\t \x03(\tR\x0eblockedDomains\x1aC\n" +
	"\x15CollectorConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xce\x01\n" +
	"\tLogConfig\x12.\n" +
	"\x05level\x18\x01 \x01(\x0e2\x18.openedr.common.LogLevelR\x05level\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\"\n" +
	"\rmax_file_size\x18\x04 \x01(\x05R\vmaxFileSize\x12\x1f\n" +
	"\vmax_backups\x18\x05 \x01(\x05R\n" +
	"maxBackups\x12\x17\n" +
	"\amax_age\x18\x06 \x01(\x05R\x06maxAge\"\xd2\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x122\n" +
	"\x06status\x18\x03 \x01(\v2\x1a.openedr.agent.AgentStatusR\x06status\x125\n" +
	"\ametrics\x18\x04 \x01(\v2\x1b.openedr.agent.AgentMetricsR\ametrics\"\x8b\x02\n" +
	"\vAgentStatus\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x122\n" +
	"\x06uptime\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06uptime\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12+\n" +
	"\x11active_collectors\x18\x04 \x03(\tR\x10activeCollectors\x12)\n" +
	"\x10events_processed\x18\x05 \x01(\x03R\x0feventsProcessed\x12\x1f\n" +
	"\vevents_sent\x18\x06 \x01(\x03R\n" +
	"eventsSent\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError\"\xed\x02\n" +
	"\fAgentMetrics\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x03R\vmemoryUsage\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x03 \x01(\x03R\tdiskUsage\x12-\n" +
	"\x12active_connections\x18\x04 \x01(\x05R\x11activeConnections\x12*\n" +
	"\x11events_per_second\x18\x05 \x01(\x03R\x0feventsPerSecond\x12^\n" +
	"\x11collector_metrics\x18\x06 \x03(\v21.openedr.agent.AgentMetrics.CollectorMetricsEntryR\x10collectorMetrics\x1aC\n" +
	"\x15CollectorMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x88\x02\n" +
	"\x11HeartbeatResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.openedr.common.ResponseR\bresponse\x12A\n" +
	"\x0enext_heartbeat\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rnextHeartbeat\x127\n" +
	"\bcommands\x18\x03 \x03(\v2\x1b.openedr.agent.AgentCommandR\bcommands\x12A\n" +
	"\x0eupdated_config\x18\x04 \x01(\v2\x1a.openedr.agent.AgentConfigR\rupdatedConfig\"\x97\x02\n" +
	"\fAgentCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12!\n" +
	"\fcommand_type\x18\x02 \x01(\tR\vcommandType\x12K\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2+.openedr.agent.AgentCommand.ParametersEntryR\n" +
	"parameters\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe4\x01\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.openedr.common.StatusR\x06status\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12;\n" +
	"\vexecuted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAt\"m\n" +
	"\x13ReportEventsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12;\n" +
	"\vevent_batch\x18\x02 \x01(\v2\x1a.openedr.events.EventBatchR\n" +
	"eventBatch\"\xca\x01\n" +
	"\x14ReportEventsResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.openedr.common.ResponseR\bresponse\x12'\n" +
	"\x0fevents_received\x18\x02 \x01(\x05R\x0eeventsReceived\x12)\n" +
	"\x10events_processed\x18\x03 \x01(\x05R\x0feventsProcessed\x12(\n" +
	"\x10failed_event_ids\x18\x04 \x03(\tR\x0efailedEventIds\"T\n" +
	"\x10GetConfigRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12%\n" +
	"\x0econfig_version\x18\x02 \x01(\tR\rconfigVersion\"\xa4\x01\n" +
	"\x11GetConfigResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.openedr.common.ResponseR\bresponse\x122\n" +
	"\x06config\x18\x02 \x01(\v2\x1a.openedr.agent.AgentConfigR\x06config\x12%\n" +
	"\x0econfig_version\x18\x03 \x01(\tR\rconfigVersion\"\xbf\x02\n" +
	"\bLogEntry\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12.\n" +
	"\x05level\x18\x02 \x01(\x0e2\x18.openedr.common.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\tcomponent\x18\x05 \x01(\tR\tcomponent\x12;\n" +
	"\x06fields\x18\x06 \x03(\v2#.openedr.agent.LogEntry.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x11ReportLogsRequest\x12+\n" +
	"\x04logs\x18\x01 \x03(\v2\x17.openedr.agent.LogEntryR\x04logs\"o\n" +
	"\x12ReportLogsResponse\x124\n" +
	"\bresponse\x18\x01 \x01(\v2\x18.openedr.common.ResponseR\bresponse\x12#\n" +
	"\rlogs_received\x18\x02 \x01(\x05R\flogsReceived2\xbb\x04\n" +
	"\fAgentService\x12K\n" +
	"\bRegister\x12\x1e.openedr.agent.RegisterRequest\x1a\x1f.openedr.agent.RegisterResponse\x12N\n" +
	"\tHeartbeat\x12\x1f.openedr.agent.HeartbeatRequest\x1a .openedr.agent.HeartbeatResponse\x12[\n" +
	"\fReportEvents\x12\".openedr.agent.ReportEventsRequest\x1a#.openedr.agent.ReportEventsResponse(\x010\x01\x12N\n" +
	"\tGetConfig\x12\x1f.openedr.agent.GetConfigRequest\x1a .openedr.agent.GetConfigResponse\x12M\n" +
	"\x13ReportCommandResult\x12\x1c.openedr.agent.CommandResult\x1a\x18.openedr.common.Response\x12Q\n" +
	"\n" +
	"ReportLogs\x12 .openedr.agent.ReportLogsRequest\x1a!.openedr.agent.ReportLogsResponse\x12?\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x18.openedr.common.ResponseB4Z2github.com/XXXXD-cation/OpenEDR/shared/proto/agentb\x06proto3"

var (
	file_shared_proto_agent_service_proto_rawDescOnce sync.Once
	file_shared_proto_agent_service_proto_rawDescData []byte
)

func file_shared_proto_agent_service_proto_rawDescGZIP() []byte {
	file_shared_proto_agent_service_proto_rawDescOnce.Do(func() {
		file_shared_proto_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_agent_service_proto_rawDesc), len(file_shared_proto_agent_service_proto_rawDesc)))
	})
	return file_shared_proto_agent_service_proto_rawDescData
}

var file_shared_proto_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_shared_proto_agent_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),      // 0: openedr.agent.RegisterRequest
	(*RegisterResponse)(nil),     // 1: openedr.agent.RegisterResponse
	(*AgentConfig)(nil),          // 2: openedr.agent.AgentConfig
	(*LogConfig)(nil),            // 3: openedr.agent.LogConfig
	(*HeartbeatRequest)(nil),     // 4: openedr.agent.HeartbeatRequest
	(*AgentStatus)(nil),          // 5: openedr.agent.AgentStatus
	(*AgentMetrics)(nil),         // 6: openedr.agent.AgentMetrics
	(*HeartbeatResponse)(nil),    // 7: openedr.agent.HeartbeatResponse
	(*AgentCommand)(nil),         // 8: openedr.agent.AgentCommand
	(*CommandResult)(nil),        // 9: openedr.agent.CommandResult
	(*ReportEventsRequest)(nil),  // 10: openedr.agent.ReportEventsRequest
	(*ReportEventsResponse)(nil), // 11: openedr.agent.ReportEventsResponse
	(*GetConfigRequest)(nil),     // 12: openedr.agent.GetConfigRequest
	(*GetConfigResponse)(nil),    // 13: openedr.agent.GetConfigResponse
	(*LogEntry)(nil),             // 14: openedr.agent.LogEntry
	(*ReportLogsRequest)(nil),    // 15: openedr.agent.ReportLogsRequest
	(*ReportLogsResponse)(nil),   // 16: openedr.agent.ReportLogsResponse
	nil,                          // 17: openedr.agent.AgentConfig.CollectorConfigsEntry
	nil,                          // 18: openedr.agent.AgentMetrics.CollectorMetricsEntry
	nil,                          // 19: openedr.agent.AgentCommand.ParametersEntry
	nil,                          // 20: openedr.agent.LogEntry.FieldsEntry
	(*common.AgentInfo)(nil),     // 21: openedr.common.AgentInfo
	(*common.Response)(nil),      // 22: openedr.common.Response
	(*timestamp.Timestamp)(nil),  // 23: google.protobuf.Timestamp
	(common.LogLevel)(0),         // 24: openedr.common.LogLevel
	(common.Status)(0),           // 25: openedr.common.Status
	(*events.EventBatch)(nil),    // 26: openedr.events.EventBatch
	(*empty.Empty)(nil),          // 27: google.protobuf.Empty
}
var file_shared_proto_agent_service_proto_depIdxs = []int32{
	21, // 0: openedr.agent.RegisterRequest.agent_info:type_name -> openedr.common.AgentInfo
	22, // 1: openedr.agent.RegisterResponse.response:type_name -> openedr.common.Response
	2,  // 2: openedr.agent.RegisterResponse.config:type_name -> openedr.agent.AgentConfig
	23, // 3: openedr.agent.RegisterResponse.next_heartbeat:type_name -> google.protobuf.Timestamp
	17, // 4: openedr.agent.AgentConfig.collector_configs:type_name -> openedr.agent.AgentConfig.CollectorConfigsEntry
	3,  // 5: openedr.agent.AgentConfig.log_config:type_name -> openedr.agent.LogConfig
	24, // 6: openedr.agent.LogConfig.level:type_name -> openedr.common.LogLevel
	23, // 7: openedr.agent.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 8: openedr.agent.HeartbeatRequest.status:type_name -> openedr.agent.AgentStatus
	6,  // 9: openedr.agent.HeartbeatRequest.metrics:type_name -> openedr.agent.AgentMetrics
	23, // 10: openedr.agent.AgentStatus.uptime:type_name -> google.protobuf.Timestamp
	18, // 11: openedr.agent.AgentMetrics.collector_metrics:type_name -> openedr.agent.AgentMetrics.CollectorMetricsEntry
	22, // 12: openedr.agent.HeartbeatResponse.response:type_name -> openedr.common.Response
	23, // 13: openedr.agent.HeartbeatResponse.next_heartbeat:type_name -> google.protobuf.Timestamp
	8,  // 14: openedr.agent.HeartbeatResponse.commands:type_name -> openedr.agent.AgentCommand
	2,  // 15: openedr.agent.HeartbeatResponse.updated_config:type_name -> openedr.agent.AgentConfig
	19, // 16: openedr.agent.AgentCommand.parameters:type_name -> openedr.agent.AgentCommand.ParametersEntry
	23, // 17: openedr.agent.AgentCommand.expires_at:type_name -> google.protobuf.Timestamp
	25, // 18: openedr.agent.CommandResult.status:type_name -> openedr.common.Status
	23, // 19: openedr.agent.CommandResult.executed_at:type_name -> google.protobuf.Timestamp
	26, // 20: openedr.agent.ReportEventsRequest.event_batch:type_name -> openedr.events.EventBatch
	22, // 21: openedr.agent.ReportEventsResponse.response:type_name -> openedr.common.Response
	22, // 22: openedr.agent.GetConfigResponse.response:type_name -> openedr.common.Response
	2,  // 23: openedr.agent.GetConfigResponse.config:type_name -> openedr.agent.AgentConfig
	24, // 24: openedr.agent.LogEntry.level:type_name -> openedr.common.LogLevel
	23, // 25: openedr.agent.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	20, // 26: openedr.agent.LogEntry.fields:type_name -> openedr.agent.LogEntry.FieldsEntry
	14, // 27: openedr.agent.ReportLogsRequest.logs:type_name -> openedr.agent.LogEntry
	22, // 28: openedr.agent.ReportLogsResponse.response:type_name -> openedr.common.Response
	0,  // 29: openedr.agent.AgentService.Register:input_type -> openedr.agent.RegisterRequest
	4,  // 30: openedr.agent.AgentService.Heartbeat:input_type -> openedr.agent.HeartbeatRequest
	10, // 31: openedr.agent.AgentService.ReportEvents:input_type -> openedr.agent.ReportEventsRequest
	12, // 32: openedr.agent.AgentService.GetConfig:input_type -> openedr.agent.GetConfigRequest
	9,  // 33: openedr.agent.AgentService.ReportCommandResult:input_type -> openedr.agent.CommandResult
	15, // 34: openedr.agent.AgentService.ReportLogs:input_type -> openedr.agent.ReportLogsRequest
	27, // 35: openedr.agent.AgentService.HealthCheck:input_type -> google.protobuf.Empty
	1,  // 36: openedr.agent.AgentService.Register:output_type -> openedr.agent.RegisterResponse
	7,  // 37: openedr.agent.AgentService.Heartbeat:output_type -> openedr.agent.HeartbeatResponse
	11, // 38: openedr.agent.AgentService.ReportEvents:output_type -> openedr.agent.ReportEventsResponse
	13, // 39: openedr.agent.AgentService.GetConfig:output_type -> openedr.agent.GetConfigResponse
	22, // 40: openedr.agent.AgentService.ReportCommandResult:output_type -> openedr.common.Response
	16, // 41: openedr.agent.AgentService.ReportLogs:output_type -> openedr.agent.ReportLogsResponse
	22, // 42: openedr.agent.AgentService.HealthCheck:output_type -> openedr.common.Response
	36, // [36:43] is the sub-list for method output_type
	29, // [29:36] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_shared_proto_agent_service_proto_init() }
func file_shared_proto_agent_service_proto_init() {
	if File_shared_proto_agent_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_agent_service_proto_rawDesc), len(file_shared_proto_agent_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_agent_service_proto_goTypes,
		DependencyIndexes: file_shared_proto_agent_service_proto_depIdxs,
		MessageInfos:      file_shared_proto_agent_service_proto_msgTypes,
	}.Build()
	File_shared_proto_agent_service_proto = out.File
	file_shared_proto_agent_service_proto_goTypes = nil
	file_shared_proto_agent_service_proto_depIdxs = nil
}
